// <auto-generated />
namespace Semec.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addmigation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmigation));
        
        string IMigrationMetadata.Id
        {
            get { return "202112171134167_add-migation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
